export default () => ({
    db_url: process.env.DATABASE_URL!,
    jwt_secret: process.env.JWT_SECRET!,
    node_env: process.env.NODE_ENV || 'development',
    resend_api_key: process.env.RESEND_API_KEY!,
    frontend_url: process.env.FRONTEND_URL || 'http://localhost:3000',
    R2_ACCOUNT_ID: process.env.R2_ACCOUNT_ID!,
    R2_ACCESS_KEY_ID: process.env.R2_ACCESS_KEY_ID!,
    R2_SECRET_ACCESS_KEY: process.env.R2_SECRET_ACCESS_KEY!,
    R2_BUCKET_NAME: process.env.R2_BUCKET_NAME!,
    R2_PUBLIC_URL: process.env.R2_PUBLIC_URL!,
    R2_S3_API: process.env.R2_S3_API!,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN!,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL!,
})